# Generated by Django 5.0.1 on 2024-04-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0003_remove_project_assigned_user_project_assigned_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystatusreport',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='hours worked'),
        ),
    ]
