# Generated by Django 5.0.1 on 2024-04-07 06:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0004_alter_dailystatusreport_hours_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystatusreport',
            name='created_by',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='dailystatusreport',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='dailystatusreport',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dailystatusreport',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dailystatusreport',
            name='updated_by',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
