"""empty message

Revision ID: 27d374f4bed2
Revises: 93bf58a3985b
Create Date: 2023-12-30 22:13:32.699283

"""
from alembic import op
import sqlalchemy as sa
from db import models

# revision identifiers, used by Alembic.
revision = '27d374f4bed2'
down_revision = '93bf58a3985b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_token',
    sa.Column('user_id', models.ULIDType(length=26), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_token_access_token'), ['access_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_token_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_token_refresh_token'), ['refresh_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_token_refresh_token'))
        batch_op.drop_index(batch_op.f('ix_auth_token_is_active'))
        batch_op.drop_index(batch_op.f('ix_auth_token_access_token'))

    op.drop_table('auth_token')
    # ### end Alembic commands ###
