# Generated by Django 5.0.1 on 2024-02-04 06:46

import DSR.utils
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', DSR.utils.ULIDField(editable=False, max_length=26, verbose_name='address id')),
                ('address_1', models.CharField(max_length=100, verbose_name='address 1')),
                ('address_2', models.CharField(max_length=100, verbose_name='address 2')),
                ('zip_code', models.CharField(max_length=50, verbose_name='zip code')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', DSR.utils.ULIDField(editable=False, max_length=26, verbose_name='country ulid')),
                ('name', models.CharField(max_length=255, verbose_name='country name')),
                ('isd_code', models.CharField(max_length=50, verbose_name='isd code')),
                ('alpha2', models.CharField(max_length=100, verbose_name='alpha 2')),
                ('alpha3', models.CharField(max_length=100, verbose_name='apha 3')),
                ('currency', models.CharField(max_length=100, verbose_name='currency')),
                ('currency_symbol', models.CharField(max_length=100, verbose_name='currency symbol')),
                ('currency_code', models.CharField(max_length=100, verbose_name='currency code')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='InvitationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', DSR.utils.ULIDField(editable=False, max_length=26, verbose_name='invitation id')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('token', models.TextField()),
                ('expiry_date', models.DateTimeField(verbose_name='expires at')),
            ],
            options={
                'verbose_name': 'Invitation History',
                'verbose_name_plural': 'Invitation History',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', DSR.utils.ULIDField(editable=False, max_length=26, verbose_name='role id')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='role slug')),
                ('name', models.CharField(max_length=100, verbose_name='role name')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', DSR.utils.ULIDField(editable=False, max_length=26, verbose_name='branch id')),
                ('branch_name', models.CharField(max_length=100, verbose_name='branch name')),
                ('branch_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.address')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', DSR.utils.ULIDField(editable=False, max_length=26, verbose_name='company id')),
                ('name', models.CharField(max_length=100, verbose_name='company name')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='user.branch')),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profiles',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.country'),
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', DSR.utils.ULIDField(editable=False, max_length=26, verbose_name='phone ulid')),
                ('phone', models.CharField(blank=True, help_text='phone number', verbose_name='phone number')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.country')),
            ],
            options={
                'verbose_name': 'Phone Number',
                'verbose_name_plural': 'Phone Numbers',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', DSR.utils.ULIDField(editable=False, max_length=26, verbose_name='user id')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('secondary_email', models.EmailField(help_text='secondary email address', max_length=254, verbose_name='secondary email')),
                ('first_name', models.CharField(help_text='First Name of the User', max_length=254, verbose_name='first name')),
                ('last_name', models.CharField(help_text='Last Name of the User', max_length=254, verbose_name='last name')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6, verbose_name='sex')),
                ('dob', models.DateTimeField(auto_now_add=True, verbose_name='date of birth')),
                ('employee_code', models.CharField(max_length=50, verbose_name='employee code')),
                ('joining_date', models.DateField(auto_now=True, verbose_name='joining date')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is staff')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.address')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.companyprofile')),
                ('phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.phonenumber')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.role')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', DSR.utils.ULIDField(editable=False, max_length=26, verbose_name='invitation id')),
                ('first_name', models.CharField(max_length=254, verbose_name='first name')),
                ('last_name', models.CharField(max_length=254, verbose_name='last name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('inviter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tenant.tenant')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='user.role')),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', DSR.utils.ULIDField(editable=False, max_length=26, verbose_name='state uuid')),
                ('name', models.CharField(max_length=255, verbose_name='state name')),
                ('iso_code', models.CharField(max_length=2, verbose_name='iso code')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.country')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.state'),
        ),
    ]
