# Generated by Django 5.0.1 on 2024-04-05 05:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_role_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='branch',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_email',
            field=models.CharField(null=True, verbose_name='company email'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_phone',
            field=models.CharField(null=True, verbose_name='company phone'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_type',
            field=models.CharField(null=True, verbose_name='company type'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='incorporation_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='registration_number',
            field=models.CharField(null=True, verbose_name='company registration'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_branch', to='user.branch'),
        ),
    ]
