# Generated by Django 5.0.1 on 2024-04-06 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('user', '0004_branch_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_roles', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_users', to='user.branch'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='user.companyprofile'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_users', to='user.role'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_users', to='tenant.tenant'),
        ),
    ]
