# Generated by Django 5.0.1 on 2024-04-13 17:58

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfig',
            name='logo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='primary_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='secondary_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='tenant_tagline',
            field=models.TextField(db_index=True, null=True, verbose_name='tenant tagline'),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='tertiary_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AlterUniqueTogether(
            name='tenantconfig',
            unique_together={('tenant',)},
        ),
        migrations.DeleteModel(
            name='TenantTheme',
        ),
    ]
