# Generated by Django 5.0.1 on 2024-04-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_tenantconfig_logo_tenantconfig_primary_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name': 'Tenant', 'verbose_name_plural': 'Tenants'},
        ),
        migrations.AlterModelOptions(
            name='tenantconfig',
            options={'verbose_name': 'Tenant Configurations', 'verbose_name_plural': 'Tenant Configurations'},
        ),
        migrations.RenameField(
            model_name='tenantconfig',
            old_name='tenant_tagline',
            new_name='tagline',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='url',
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='url',
            field=models.URLField(null=True, unique=True, verbose_name='tenant url'),
        ),
    ]
