# Generated by Django 5.0.1 on 2024-02-04 06:46

import DSR.utils
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', DSR.utils.ULIDField(editable=False, max_length=26, verbose_name='tenant id')),
                ('name', models.CharField(max_length=100, verbose_name='tenant name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='tenant slug')),
                ('url', models.URLField(unique=True, verbose_name='tenant url')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', DSR.utils.ULIDField(editable=False, max_length=26, verbose_name='tenant config id')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_config', to='tenant.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.CharField(blank=True, max_length=500)),
                ('internal_id', DSR.utils.ULIDField(editable=False, max_length=26, verbose_name='tenant theme id')),
                ('logo', models.ImageField(blank=True, upload_to='', verbose_name='logo')),
                ('primary_color', models.CharField(max_length=10, null=True, verbose_name='primary color')),
                ('secondary_color', models.CharField(max_length=10, null=True, verbose_name='secondary color')),
                ('tertiary_color', models.CharField(max_length=10, null=True, verbose_name='tertiary color')),
                ('tenant_tagline', models.TextField(db_index=True, null=True, verbose_name='tenant tagline')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_theme', to='tenant.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
